import type { Metadata } from "next";
import "./globals.css";
import { AppKit } from "@/context/web3modal";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<AppKit>{children}</AppKit>
			</body>
		</html>
	);
}
