export type Market = {
	id: number;
	name: string;
	token1: string;
	token2: string;
	odds: number;
	exchange: string;
	oracle: {
		name: string;
		address: string;
		isVerified: boolean;
	};
	creator: {
		name: string;
		address: string;
		isVerified: boolean;
	};
	expiryDate: string;
	isVerified: boolean;
	isRisky: boolean;
	matchScore?: number;
};

export const mockMarkets: Market[] = [
	{
		id: 1,
		name: "Trump ends Ukraine war by first 90 days?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.5,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-11-05T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 2,
		name: "Bitcoin Price $100k in 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.0,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 3,
		name: "Jake Paul vs. Mike Tyson fight rigged?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.2,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-06-30T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 4,
		name: "Will Vitalik Buterin write a next blog about Prediction Markets?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.2,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234(world id)",
			isVerified: false,
		},
		creator: {
			name: "worldcoin",
			address: "0x9876...1234(world id)",
			isVerified: false,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 5,
		name: "OpenAI announces it has achieved AGI in 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.8,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 6,
		name: "AI on Amazon speaker by June?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.4,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-06-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 7,
		name: "Tesla Cybertruck delivery exceeds 100k in 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.1,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 8,
		name: "Apple Vision Pro sales exceed 1M units by July?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.9,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-07-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 9,
		name: "Meta launches decentralized social network in 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.5,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 10,
		name: "SpaceX Starship reaches orbit by September?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.6,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-09-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 11,
		name: "Google releases Gemini Advanced mobile app?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.3,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-06-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 12,
		name: "Microsoft acquires AI startup valued >$1B?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.2,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 13,
		name: "Ethereum moves to full PoS by October?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.8,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-10-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 14,
		name: "Netflix launches AI-generated content series?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.7,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 15,
		name: "Amazon drone delivery in 100+ cities?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.4,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 16,
		name: "Apple announces AI chatbot assistant?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.5,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-09-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 17,
		name: "Twitter daily active users reach 1B?",
		token1: "USDC",
		token2: "USDC",
		odds: 3.0,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 18,
		name: "Samsung releases AI smartphone chip?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.4,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-08-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 19,
		name: "Intel regains semiconductor market lead?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.6,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 20,
		name: "Nvidia launches consumer AI PC by November?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.8,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-11-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 21,
		name: "Will Sony release PlayStation VR3 by December 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.3,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 22,
		name: "Will Coinbase achieve 100M verified users by Q3 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.9,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-09-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 23,
		name: "Will Discord launch its IPO before September 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.1,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-09-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 24,
		name: "Will SpaceX successfully land Starship on Mars by October 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 3.5,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-10-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 25,
		name: "Will Anthropic's Claude surpass GPT-4 in MMLU benchmarks by July 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.8,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-07-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 26,
		name: "Will Solana reach 100k TPS in mainnet by August 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.4,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-08-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 27,
		name: "Will Toyota release a fully autonomous vehicle by December 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.7,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 28,
		name: "Will Reddit achieve 1B monthly active users by November 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.2,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-11-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 29,
		name: "Will Stripe acquire a crypto company by October 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.6,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-10-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 30,
		name: "Will Adobe release an AI-first video editor by September 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.7,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-09-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 31,
		name: "Will Unity Engine support quantum computing by December 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 4.0,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 32,
		name: "Will Robinhood launch crypto staking for 10+ tokens by July 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.9,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-07-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 33,
		name: "Will Palantir secure $10B+ in government contracts by November 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.3,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-11-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 34,
		name: "Will Binance obtain licenses in 50+ countries by December 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.1,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 35,
		name: "Will Spotify launch AI-generated music features by August 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.5,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-08-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 36,
		name: "Will Uber achieve profitability for 4 consecutive quarters by Q4 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.0,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-12-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 37,
		name: "Will Roblox launch adult-focused metaverse platform by October 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.8,
		exchange: "Polymarket",
		oracle: {
			name: "uma",
			address: "0x1234...5678",
			isVerified: true,
		},
		creator: {
			name: "Polymarket Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-10-31T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
	{
		id: 38,
		name: "Will Ripple achieve settlement with SEC by September 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 1.8,
		exchange: "Uniswap",
		oracle: {
			name: "worldcoin",
			address: "0x9876...1234",
			isVerified: false,
		},
		creator: {
			name: "Unknown Creator",
			address: "0x9876...1234",
			isVerified: false,
		},
		expiryDate: "2024-09-30T00:00:00Z",
		isVerified: false,
		isRisky: true,
	},
	{
		id: 39,
		name: "Will DoorDash expand to 30+ new countries by November 2024?",
		token1: "USDC",
		token2: "USDC",
		odds: 2.5,
		exchange: "Kalshi",
		oracle: {
			name: "chainlink",
			address: "0x8765...4321",
			isVerified: true,
		},
		creator: {
			name: "Kalshi Official",
			address: "0x8765...4321",
			isVerified: true,
		},
		expiryDate: "2024-11-30T00:00:00Z",
		isVerified: true,
		isRisky: false,
	},
];
