import { MarketWidget } from "@/lib/interface";

export const demoMarketsData: MarketWidget[] = [
	{
		newsId: 1,
		marketId: 1,
		marketName: "Will Polymarket Founder be arrested by June 2024?",
		marketPrice: 0.65,
		marketChange24h: 35,
		marketVolume: 250000,
		marketParticipants: 1200,
		marketStatus: "Active",
		marketCreators: ["Polymarket"],
		marketOracle: ["Uma", "Polymarket"],
		marketCategory: ["Politics", "Crypto"],
	},
	{
		newsId: 1,
		marketId: 2,
		marketName: "Polymarket will continue to operate until the end of 2024",
		marketPrice: 0.45,
		marketChange24h: -15,
		marketVolume: 180000,
		marketParticipants: 800,
		marketStatus: "End Soon",
		marketCreators: ["Polymarket"],
		marketOracle: ["Uma"],
		marketCategory: ["Politics", "Crypto"],
	},
	{
		newsId: 1,
		marketId: 3,
		marketName: "Will SEC take legal action against Polymarket?",
		marketPrice: 0.78,
		marketChange24h: 20,
		marketVolume: 320000,
		marketParticipants: 1500,
		marketStatus: "New",
		marketCreators: ["Polymarket"],
		marketOracle: ["Uma"],
		marketCategory: ["Politics", "Crypto"],
	},
	{
		newsId: 1,
		marketId: 4,
		marketName: "Will 50% of Polymarket's assets be frozen?",
		marketPrice: 0.55,
		marketChange24h: 8,
		marketVolume: 150000,
		marketParticipants: 650,
		marketStatus: "Finished",
		marketCreators: ["Polymarket"],
		marketOracle: ["Uma"],
		marketCategory: ["Politics", "Crypto"],
	},
];
